#configuration file of the controllers + gains + other params to pass on the server

P_gains: [200.0, 90.0, 170.0, 1100.0, 2200.0, 14000.0]

D_gains: [50.0, 6.0, 5.0, 60.0, 25.0, 15.0]

#target_positions: [4.8, 2.9, 1.0, 4.2, 1.5, 1.25] #home position
target_positions: [5.3, 3.3, 1.5, 4.5, 0.8, 1.85] # trial position #1 [short]
#target_positions: [4.0, 3.7, 1.8, 3.4, 2.3, 0.45] # trial position #2 [medium]

#Publishing rate for planner/controller -- 100hz seems to be max, same as default trajectory controller used by robot
param_publish_rate : 100


